-------------------------------------------------------------------------------
-- Dump everything the editor grammars need to know about Macaulay2 into
-- syntaxes/m2-tokens.json, then let scripts/generate-syntax.js expand the
-- .in templates.
--
-- The templating deliberately happens in node rather than here.  Keeping the
-- substitution step in plain JavaScript -- with m2-tokens.json checked in --
-- lets the tests verify that the committed grammars match their templates
-- without starting Macaulay2.  (M2's replace also reads backslashes in the
-- replacement text as backreferences, which the operator alternations are
-- full of.)
--
-- Run via "npm run update", which invokes this and then the node script.
-------------------------------------------------------------------------------

needsPackage "Style"
needsPackage "JSON"

importFrom(Core, "getParsing")

-------------------------------------------------------------------------------
-- Symbols.  Style bins these for us; generating completionProviders.ts is what
-- populates its cache.
-------------------------------------------------------------------------------

generateGrammar("src/backend/completionProviders.ts", x -> demark(", ", format \ x))

cachedSymbols = value (Style#"private dictionary")#"cachedSymbols"
if #cachedSymbols == 0 then error "Style did not populate cachedSymbols"

-------------------------------------------------------------------------------
-- Operators.
--
-- Style's own symbol bins cannot help here: its "okay" filter keeps only names
-- that are alphanumeric and longer than one character, which excludes every
-- symbolic operator by construction.  So walk the keywords ourselves and ask
-- the interpreter what it does with each one.
--
-- getParsing returns {precedence, binaryStrength, unaryStrength}.  Every
-- assignment-like keyword answers {14, 13, -1}, which is what separates them
-- from the rest; nothing else in the dictionary shares that signature.
--
-- The delimiters below are keywords too, and would otherwise be scoped as
-- operators -- painting every parenthesis in the editor.
-------------------------------------------------------------------------------

delimiters = {
    symbol (, symbol ),
    symbol [, symbol ],
    symbol {, symbol },
    symbol <|, symbol |>,
    symbol ,, symbol ;}

isAlphaNumeric = s -> match("^[[:alnum:]]+$", s)

-- Alphanumeric keywords (and, or, if, then, ...) are already covered by
-- Style's keyword list, so only the symbolic ones are collected here.
operators = sort unique(toString \ select(values Core.Dictionary,
	k -> instance(k, Keyword)
	and not isAlphaNumeric toString k
	and not isMember(k, delimiters)))

assignmentSignature = {14, 13, -1}
isAssignment = s -> getParsing getGlobalSymbol s == assignmentSignature

-- The formatter puts spaces around these.  It must not be given the full
-- operator list: spacing every operator would rewrite a^2 as a ^ 2 and x_1 as
-- x _ 1.  "++" is the one spaced operator with neither "=" nor an arrow in it.
spacedOperators = sort unique join(
    select(operators, s -> match("=", s)),
    {"->", "<-", "++"})

-------------------------------------------------------------------------------
-- SimpleDoc keywords.
--
-- Only the keyword *names* come from M2.  Which body form each one takes --
-- prose, Macaulay2 code, verbatim text -- is decided inside the handler
-- functions, not recorded in the tables, so generate-syntax.js hard-codes that
-- mapping.  Reading the names here lets it fail loudly when the two disagree
-- rather than silently leaving a new keyword unhighlighted.
-------------------------------------------------------------------------------

simpleDocTable = name -> sort keys value (SimpleDoc#"private dictionary")#name

-------------------------------------------------------------------------------

tokens = hashTable {
    "comment" => "Generated by generate-grammar.m2 -- do not edit by hand.",
    "version" => version#"VERSION",
    "symbols" => hashTable {
	"keywords"  => cachedSymbols.Keyword,
	"types"     => cachedSymbols.Type,
	"functions" => cachedSymbols.Function,
	"constants" => cachedSymbols.Constant},
    "operators" => hashTable {
	"assignment" => select(operators, isAssignment),
	"other"      => select(operators, s -> not isAssignment s),
	"spaced"     => spacedOperators},
    "simpledoc" => hashTable {
	"node"         => simpleDocTable "NodeFunctions",
	"synopsis"     => simpleDocTable "SynopsisFunctions",
	"description"  => simpleDocTable "DescriptionFunctions",
	"consequences" => simpleDocTable "ConsequencesFunctions"}}

printerr("generating syntaxes/m2-tokens.json")
f = openOut "syntaxes/m2-tokens.json"
f << toJSON(tokens, Indent => 2, Sort => true) << endl << close
